# Generated by Django 3.0.3 on 2020-02-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umpires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.CharField(max_length=8)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='umpire',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
